"""SW-1 EiBi parser, persistence, and bounded-query qualification tests.

The fixture is intentionally small but field-complete.  It exercises the
same semicolon-delimited shape as the audited A26 file while keeping tests
isolated from the user's RadioTools corpus and runtime databases.
"""

from __future__ import annotations

import importlib
import inspect
import json
import sqlite3
import time
from collections.abc import Mapping
from pathlib import Path
from typing import Any

import pytest


FIXTURE = Path(__file__).parent / "fixtures" / "eibi_sw1_field_grammar.csv"
README_FIXTURE = Path("/Users/bill/RadioTools/Programs/shortwave/eibi_README.TXT")


def _field(value: object, *names: str, default: Any = None) -> Any:
    """Read a model field while allowing the implementation's DTO spelling."""

    if isinstance(value, Mapping):
        for name in names:
            if name in value:
                return value[name]
        return default
    for name in names:
        if hasattr(value, name):
            return getattr(value, name)
    return default


def _parser_module():
    for name in (
        "freqinout.core.shortwave_eibi",
        "freqinout.core.shortwave_provider",
        "freqinout.core.shortwave_parser",
        "freqinout.core.shortwave_eibi_provider",
    ):
        try:
            return importlib.import_module(name)
        except ModuleNotFoundError:
            continue
    pytest.fail("SW-1 must provide a Qt-free EiBi parser module")


def _parse_fixture(*, season_code: str = "A26", season_from: str | None = "2026-04-01T00:00:00Z", season_to: str | None = "2026-10-31T23:59:59Z") -> Any:
    module = _parser_module()
    raw = FIXTURE.read_bytes()
    readme = README_FIXTURE.read_bytes()
    adapter_type = getattr(module, "EiBiProviderAdapter", None)
    if adapter_type is not None:
        adapter = adapter_type()
        parse = getattr(adapter, "parse", None)
        if callable(parse):
            return parse(
                raw,
                readme,
                season_code=season_code,
                season_effective_from_utc=season_from,
                season_effective_to_utc=season_to,
            )
    parser_type = getattr(module, "EiBiParser", None)
    if parser_type is not None:
        signature = inspect.signature(parser_type)
        values = {
            "season_code": season_code,
            "season_effective_from_utc": season_from,
            "season_effective_to_utc": season_to,
            "encoding": "iso-8859-1",
        }
        parser = parser_type(**{key: value for key, value in values.items() if key in signature.parameters})
        for method_name, argument in (("parse_bytes", raw), ("parse", raw), ("parse_file", FIXTURE)):
            method = getattr(parser, method_name, None)
            if callable(method):
                return method(argument)

    function = getattr(module, "parse_eibi_csv", None)
    if callable(function):
        signature = inspect.signature(function)
        values = {
            "season_code": season_code,
            "season_effective_from_utc": season_from,
            "season_effective_to_utc": season_to,
            "encoding": "iso-8859-1",
        }
        kwargs = {key: value for key, value in values.items() if key in signature.parameters}
        for arguments in ((raw, readme), (raw, FIXTURE), (raw,)):
            try:
                return function(*arguments, **kwargs)
            except (TypeError, UnicodeDecodeError):
                continue
    pytest.fail("SW-1 EiBi parser must expose EiBiParser or parse_eibi_csv")


def _parse_bytes(raw: bytes, *, season_code: str = "A26") -> Any:
    """Invoke the parser with generated bytes for bounded-corpus checks."""

    module = _parser_module()
    readme = README_FIXTURE.read_bytes()
    adapter_type = getattr(module, "EiBiProviderAdapter", None)
    if adapter_type is not None:
        parse = getattr(adapter_type(), "parse", None)
        if callable(parse):
            return parse(
                raw,
                readme,
                season_code=season_code,
                season_effective_from_utc="2026-04-01T00:00:00Z",
                season_effective_to_utc="2026-10-31T23:59:59Z",
            )
    parser_type = getattr(module, "EiBiParser", None)
    if parser_type is not None:
        signature = inspect.signature(parser_type)
        kwargs = {
            key: value
            for key, value in {"season_code": season_code, "encoding": "iso-8859-1"}.items()
            if key in signature.parameters
        }
        parser = parser_type(**kwargs)
        method = getattr(parser, "parse_bytes", None) or getattr(parser, "parse", None)
        if callable(method):
            return method(raw)
    function = getattr(module, "parse_eibi_csv", None)
    if callable(function):
        signature = inspect.signature(function)
        kwargs = {
            key: value
            for key, value in {"season_code": season_code, "encoding": "iso-8859-1"}.items()
            if key in signature.parameters
        }
        return function(raw, readme, **kwargs)
    pytest.fail("SW-1 parser does not support bytes input")


def _entries(result: Any) -> list[Any]:
    for name in ("entries", "rows", "records", "schedule_entries"):
        value = _field(result, name)
        if value is not None:
            return list(value)
    if isinstance(result, (list, tuple)):
        return list(result)
    pytest.fail("EiBi parser result must expose bounded entries")


def _diagnostics(result: Any) -> list[Any]:
    value = _field(result, "diagnostics", "parse_diagnostics", default=())
    return list(value or ())


def _entry_by_station(entries: list[Any], text: str) -> Any:
    for entry in entries:
        if text in str(_field(entry, "station_name", "station", "name", default="")):
            return entry
    pytest.fail(f"fixture entry not found: {text}")


def test_fixture_preserves_audited_shape_and_latin1_decode() -> None:
    lines = FIXTURE.read_text(encoding="ascii").splitlines()
    assert len(lines[0].split(";")) == 12  # header has the documented trailing field
    assert all(len(line.split(";")) == 11 for line in lines[1:])

    # The fixture remains ASCII on disk so it is portable in source control;
    # substitute a genuine Latin-1 byte at the parser boundary.
    latin1 = FIXTURE.read_bytes().replace(b"BUE Latin-1", b"B\xfc Latin-1")
    assert b"\xfc" in latin1
    module = _parser_module()
    parser_type = getattr(module, "EiBiParser", None) or getattr(module, "EiBiProviderAdapter", None)
    assert parser_type is not None, "EiBiParser/EiBiProviderAdapter must own explicit encoding"
    signature = inspect.signature(parser_type)
    kwargs = {
        key: value
        for key, value in {"encoding": "iso-8859-1", "season_code": "A26"}.items()
        if key in signature.parameters
    }
    parser = parser_type(**kwargs)
    parse = getattr(parser, "parse_bytes", None) or getattr(parser, "parse", None)
    assert callable(parse)
    try:
        result = parse(latin1, README_FIXTURE.read_bytes(), season_code="A26", season_effective_from_utc="2026-04-01T00:00:00Z", season_effective_to_utc="2026-10-31T23:59:59Z")
    except TypeError:
        result = parse(latin1)
    station = _entry_by_station(_entries(result), "Latin-1")
    assert "ü" in str(_field(station, "station_name", "station", "name"))
    assert not any("decode" in str(_field(item, "reason", "message", default=item)).lower() for item in _diagnostics(result))


def test_bundled_a26_corpus_has_no_silent_row_loss_and_retains_provenance() -> None:
    from freqinout.core.shortwave_eibi_provider import bundled_eibi_seed_paths, parse_eibi_dataset

    csv_path, readme_path = bundled_eibi_seed_paths()
    assert csv_path.is_file() and readme_path.is_file()
    candidate = parse_eibi_dataset(
        csv_path,
        readme_path,
        season_code="A26",
        season_effective_from_utc="2026-04-01T00:00:00Z",
        season_effective_to_utc="2026-10-31T23:59:59Z",
    )
    raw_data_rows = int(candidate.metadata["raw_data_rows"])
    assert raw_data_rows == 9_442
    assert candidate.csv_sha256 == "60830fc5db384d160c17d3144bd15966d4c3f5cb9b29f4600a6d7c11eacd4dd4"
    assert candidate.readme_sha256 == "9d0227b6b1e2ce8310d4fd6f5019922f6b11062a1dc0deeaedbc54b2b8a19ffc"
    accounted_lines = {entry.source_line_number for entry in candidate.entries}
    accounted_lines.update(item.line_number for item in candidate.diagnostics if item.line_number and item.line_number > 1)
    assert accounted_lines == set(range(2, raw_data_rows + 2))
    assert "attribution" in candidate.metadata
    assert "schedule_accuracy_caveat" in candidate.metadata
    assert candidate.dictionaries
    operator_rows = [entry for entry in candidate.entries if not entry.duplicate]
    assert len({entry.provider_identity_hash for entry in operator_rows}) == len(operator_rows), (
        "distinct language/target/transmitter listings must retain distinct stable identities"
    )


def test_eibi_exact_frequency_and_utc_time_rules() -> None:
    result = _parse_fixture()
    entries = _entries(result)
    all_day = _entry_by_station(entries, "Latin-1 station")
    cross = _entry_by_station(entries, "Cross midnight")
    decimal = _entry_by_station(entries, "Numeric weekday")

    assert _field(all_day, "frequency_hz", "frequency") == 9_955_000
    assert _field(decimal, "frequency_hz", "frequency") == 12_000_500
    assert _field(all_day, "start_minute_utc", "start_minute", "start_utc_minute", "start_min") == 0
    assert _field(all_day, "end_minute_utc", "end_minute", "end_utc_minute", "end_min") == 1_440
    assert _field(all_day, "crosses_midnight", "cross_midnight", default=False) is False
    assert _field(cross, "start_minute_utc", "start_minute", "start_utc_minute", "start_min") == 1_410
    assert _field(cross, "end_minute_utc", "end_minute", "end_utc_minute", "end_min") == 90
    assert _field(cross, "crosses_midnight", "cross_midnight") is True


def test_eibi_blank_and_deterministic_days_are_distinct_from_special_rules() -> None:
    entries = _entries(_parse_fixture())
    daily = _entry_by_station(entries, "Latin-1 station")
    numeric = _entry_by_station(entries, "Numeric weekday")
    irregular = _entry_by_station(entries, "Special irregular")
    fixed = _entry_by_station(entries, "Fixed date")
    monthly = _entry_by_station(entries, "Monthly special")
    unsupported = _entry_by_station(entries, "Unsupported signal")

    assert str(_field(daily, "raw_days", "days_raw", "day_expression", default="")) == ""
    recurrence = _field(daily, "recurrence", default={})
    assert str(_field(daily, "day_rule", "normalized_day_rule", "days_rule", default="") or _field(recurrence, "kind", default="")).lower() in {"daily", "every_day", "all"}
    assert _field(numeric, "weekday_mask", "normalized_weekday_mask", "day_mask")
    for entry in (irregular, fixed, monthly, unsupported):
        state = str(_field(entry, "parse_state", "interpretation", "validation_state", default="")).lower()
        assert state and state not in {"complete", "ok", "valid"}, entry


def test_eibi_dates_last_heard_signal_language_utility_and_inactive_fields() -> None:
    entries = _entries(_parse_fixture())
    last_heard = _entry_by_station(entries, "Latin-1 station")
    bracketed = _entry_by_station(entries, "Cross midnight")
    utility = _entry_by_station(entries, "Special irregular")
    inactive = _entry_by_station(entries, "Inactive row")
    malformed_date = _entry_by_station(entries, "Malformed date")

    assert _field(last_heard, "last_heard_raw", "raw_last_heard", "last_heard") in (None, "")
    # Bracketed last-heard metadata must not become a normal stop date.
    assert "[0923]" in str(_field(bracketed, "last_heard_raw", "raw_last_heard", "last_heard", default=""))
    assert str(_field(bracketed, "stop_date_raw", "raw_stop", "stop_date", default="")) not in {"0923", "09 23"}
    assert _field(utility, "language_raw", "raw_language", "language") in {"-CW", "CW", "-cw"}
    assert _field(utility, "signal_type", "signal", "decoded_signal", default="")
    assert int(_field(utility, "persistence", "persistence_code", "raw_persistence", "persistence_raw")) >= 90
    assert bool(_field(inactive, "inactive", "is_inactive", default=False)) is True
    assert _field(malformed_date, "start_date_raw", "raw_start", "start_date") in {"3213", "32 13", ""} or _field(malformed_date, "date_diagnostic", "date_state", default="")


def test_eibi_duplicate_identity_is_preserved_and_projection_deduplicates() -> None:
    result = _parse_fixture()
    entries = _entries(result)
    duplicates = [entry for entry in entries if "Duplicate row" in str(_field(entry, "station_name", "station", "name", default=""))]
    assert len(duplicates) == 2, "source rows remain auditable even when projection deduplicates"
    duplicate_count = _field(result, "duplicate_count", "exact_duplicate_count", default=None)
    if duplicate_count is not None:
        assert int(duplicate_count) >= 1
    projection = _field(result, "projection", "deduplicated_entries", "normal_entries", default=None)
    if projection is not None:
        assert len(list(projection)) < len(entries)

    diagnostics = " ".join(str(_field(item, "reason", "message", default=item)) for item in _diagnostics(result)).lower()
    assert "malformed" in diagnostics or "review" in diagnostics or "unsupported" in diagnostics


def test_eibi_winter_manifest_requires_cross_year_season_bounds() -> None:
    result = _parse_fixture(season_code="B26", season_from="2026-10-25T00:00:00Z", season_to="2027-03-28T23:59:59Z")
    manifest = _field(result, "manifest", "dataset_manifest", default=result)
    assert _field(manifest, "season_code", "season", default="B26") == "B26"
    assert _field(manifest, "season_effective_from_utc", "effective_from_utc", default="")
    assert _field(manifest, "season_effective_to_utc", "effective_to_utc", default="")
    assert str(_field(manifest, "season_effective_to_utc", "effective_to_utc", default="")).startswith("2027-")

    with pytest.raises(ValueError, match="season_effective_from_utc"):
        _parse_fixture(season_code="A26", season_from=None, season_to=None)


def test_sw1_parser_handles_ten_thousand_rows_without_unbounded_materialization() -> None:
    header = FIXTURE.read_bytes().splitlines()[0]
    row = b"9955;0000-2400;Mo;USA;Synthetic bounded row;EN;NA;USA;1;;"
    raw = b"\n".join([header, *(row for _ in range(10_000))]) + b"\n"
    started = time.perf_counter()
    result = _parse_bytes(raw)
    elapsed = time.perf_counter() - started
    entries = _entries(result)
    assert len(entries) == 10_000
    assert elapsed < 5.0, f"10,000-row EiBi parse took {elapsed:.2f}s"


def test_sw1_parser_cancellation_and_source_limits_abort_before_partial_work() -> None:
    from freqinout.core.shortwave_eibi_provider import parse_eibi_dataset
    from freqinout.core.shortwave_models import ShortwaveImportCancelled

    raw = FIXTURE.read_bytes()
    readme = README_FIXTURE.read_bytes()
    with pytest.raises(ShortwaveImportCancelled):
        parse_eibi_dataset(
            raw,
            readme,
            season_code="A26",
            season_effective_from_utc="2026-04-01T00:00:00Z",
            season_effective_to_utc="2026-10-31T23:59:59Z",
            cancellation_probe=lambda: True,
        )
    with pytest.raises(ValueError, match="row limit"):
        parse_eibi_dataset(
            raw,
            readme,
            season_code="A26",
            season_effective_from_utc="2026-04-01T00:00:00Z",
            season_effective_to_utc="2026-10-31T23:59:59Z",
            max_rows=1,
        )


def test_sw1_malformed_rows_are_visible_in_candidate_and_persisted_diagnostics(tmp_path: Path) -> None:
    store = _store(tmp_path / "freqinout_nets.db")
    from freqinout.core.shortwave_import import apply_shortwave_import, preview_shortwave_import

    candidate = _parse_fixture()
    diagnostics = _diagnostics(candidate)
    diagnostic_lines = {int(_field(item, "line_number", "source_line_number")) for item in diagnostics}
    assert {15, 16}.issubset(diagnostic_lines)
    assert any(
        int(_field(item, "line_number", "source_line_number")) == 15
        and str(_field(item, "severity", default="")).lower() == "error"
        for item in diagnostics
    )
    malformed_time = next(entry for entry in _entries(candidate) if _field(entry, "source_line_number") == 16)
    assert str(_field(malformed_time, "parse_state", "validation_state")).lower() == "review"
    assert _field(malformed_time, "diagnostics")

    result = apply_shortwave_import(store, preview_shortwave_import(store, candidate))
    assert result.status == "promoted"
    dataset = store.current_dataset()
    assert dataset is not None
    assert dataset.diagnostic_counts.get("error", 0) >= 1
    with sqlite3.connect(store.db_path) as conn:
        payload = json.loads(conn.execute(
            "SELECT diagnostics_json FROM shortwave_datasets WHERE dataset_key=?",
            (dataset.dataset_key,),
        ).fetchone()[0])
    assert {int(item["line_number"]) for item in payload if item.get("line_number")} >= {15, 16}


def test_sw1_official_download_config_is_fixed_host_and_bounded() -> None:
    from freqinout.core.shortwave_eibi_provider import EiBiDownloadConfig

    safe = EiBiDownloadConfig(max_bytes=1000, max_redirects=2, timeout_seconds=5)
    assert safe.max_bytes == 1000
    with pytest.raises(ValueError):
        EiBiDownloadConfig(csv_url="http://www.eibispace.de/sked.csv")
    with pytest.raises(ValueError):
        EiBiDownloadConfig(csv_url="https://example.invalid/sked.csv")
    with pytest.raises(ValueError):
        EiBiDownloadConfig(max_bytes=0)
    with pytest.raises(ValueError):
        EiBiDownloadConfig(max_redirects=6)


class _FakeEiBiResponse:
    def __init__(self, payload: bytes, *, url: str, content_type: str = "text/plain") -> None:
        self._payload = payload
        self._url = url
        self.status = 200
        self.headers = {
            "Content-Type": content_type,
            "Content-Length": str(len(payload)),
        }

    def __enter__(self) -> "_FakeEiBiResponse":
        return self

    def __exit__(self, *_args: object) -> None:
        return None

    def getcode(self) -> int:
        return self.status

    def geturl(self) -> str:
        return self._url

    def read(self, size: int = -1) -> bytes:
        if size < 0:
            size = len(self._payload)
        value, self._payload = self._payload[:size], self._payload[size:]
        return value


class _FakeEiBiOpener:
    def __init__(self, responses: dict[str, _FakeEiBiResponse]) -> None:
        self.responses = responses

    def open(self, request: object, *, timeout: float) -> _FakeEiBiResponse:
        del timeout
        url = str(getattr(request, "full_url"))
        return self.responses[url]


def test_sw1_official_downloader_accepts_valid_pair_and_preserves_provenance() -> None:
    from freqinout.core.shortwave_eibi_provider import EiBiDownloadConfig, download_official_eibi

    csv_url = "https://www.eibispace.de/dx/sw1-test.csv"
    readme_url = "https://www.eibispace.de/dx/sw1-test-readme.txt"
    csv_bytes = FIXTURE.read_bytes()
    readme_bytes = README_FIXTURE.read_bytes()
    opener = _FakeEiBiOpener(
        {
            csv_url: _FakeEiBiResponse(csv_bytes, url=csv_url, content_type="text/csv"),
            readme_url: _FakeEiBiResponse(readme_bytes, url=readme_url),
        }
    )

    downloaded = download_official_eibi(
        EiBiDownloadConfig(csv_url=csv_url, readme_url=readme_url), opener=opener
    )

    assert downloaded.csv_bytes == csv_bytes
    assert downloaded.readme_bytes == readme_bytes
    assert downloaded.csv_url == csv_url
    assert downloaded.readme_url == readme_url
    assert downloaded.csv_content_type == "text/csv"
    assert downloaded.readme_content_type == "text/plain"


@pytest.mark.parametrize(
    ("asset", "content_type", "final_url", "max_bytes", "match"),
    [
        ("csv", "application/json", "https://www.eibispace.de/dx/sw1-test.csv", 2_000_000, "content type"),
        ("csv", "text/csv", "https://example.invalid/dx/sw1-test.csv", 2_000_000, "host"),
        ("csv", "text/csv", "https://www.eibispace.de/dx/sw1-test.csv", 10, "byte limit"),
    ],
)
def test_sw1_official_downloader_rejects_untrusted_shape_redirect_and_size(
    asset: str,
    content_type: str,
    final_url: str,
    max_bytes: int,
    match: str,
) -> None:
    from freqinout.core.shortwave_eibi_provider import EiBiDownloadConfig, EiBiDownloadError, download_official_eibi

    csv_url = "https://www.eibispace.de/dx/sw1-test.csv"
    readme_url = "https://www.eibispace.de/dx/sw1-test-readme.txt"
    requested_url = csv_url if asset == "csv" else readme_url
    payload = FIXTURE.read_bytes() if asset == "csv" else README_FIXTURE.read_bytes()
    opener = _FakeEiBiOpener(
        {
            requested_url: _FakeEiBiResponse(payload, url=final_url, content_type=content_type),
            readme_url: _FakeEiBiResponse(README_FIXTURE.read_bytes(), url=readme_url),
        }
    )

    with pytest.raises((EiBiDownloadError, ValueError), match=match):
        download_official_eibi(
            EiBiDownloadConfig(csv_url=csv_url, readme_url=readme_url, max_bytes=max_bytes),
            opener=opener,
        )


def _store_module():
    for name in ("freqinout.core.shortwave_store", "freqinout.core.shortwave_dataset_store"):
        try:
            return importlib.import_module(name)
        except ModuleNotFoundError:
            continue
    pytest.fail("SW-1 must provide a Qt-free Shortwave dataset store")


def _store(path: Path):
    # SW-1 is additive but depends on the canonical resource-source registry.
    from freqinout.core.resource_catalog_models import CatalogSource
    from freqinout.core.resource_catalog_store import ResourceCatalogStore

    catalog = ResourceCatalogStore(path)
    catalog.create_schema()
    if catalog.get_source("eibi") is None:
        catalog.create_source(CatalogSource("eibi", "EiBi", "bundled", read_only=True))
    module = _store_module()
    store_type = getattr(module, "ShortwaveStore", None) or getattr(module, "ShortwaveDatasetStore", None)
    assert store_type is not None
    signature = inspect.signature(store_type)
    store = store_type(path) if len(signature.parameters) else store_type()
    create_schema = getattr(store, "create_schema", None) or getattr(store, "ensure_schema", None)
    assert callable(create_schema)
    create_schema()
    return store


def test_sw1_schema_is_additive_idempotent_and_exposes_bounded_read_api(tmp_path: Path) -> None:
    db_path = tmp_path / "freqinout_nets.db"
    _store(db_path)
    with sqlite3.connect(db_path) as conn:
        conn.execute("CREATE TABLE legacy_fixture (value TEXT NOT NULL)")
        conn.execute("INSERT INTO legacy_fixture(value) VALUES ('preserve me')")
    # Re-running startup-owned schema initialization is additive and leaves
    # unrelated legacy data untouched.
    store = _store(tmp_path / "freqinout_nets.db")
    with sqlite3.connect(db_path) as conn:
        tables = {row[0] for row in conn.execute("SELECT name FROM sqlite_master WHERE type='table'")}
        preserved = conn.execute("SELECT value FROM legacy_fixture").fetchone()[0]
    assert {"resource_catalog_sources", "shortwave_datasets", "shortwave_entries"}.issubset(tables)
    assert preserved == "preserve me"
    assert callable(getattr(store, "list_entries", None) or getattr(store, "query_entries", None))
    query = getattr(store, "list_entries", None) or getattr(store, "query_entries")
    signature = inspect.signature(query)
    kwargs = {key: 200 for key in ("limit", "page_size") if key in signature.parameters}
    rows = query(**kwargs)
    assert len(rows) <= 200


def test_sw1_rejected_import_and_cancellation_leave_current_dataset_unchanged(tmp_path: Path) -> None:
    store = _store(tmp_path / "freqinout_nets.db")
    from freqinout.core.shortwave_import import apply_shortwave_import, preview_shortwave_import
    from freqinout.core.shortwave_models import ShortwaveImportCancelled

    candidate = _parse_fixture()
    preview = preview_shortwave_import(store, candidate)
    assert preview.actionable
    with pytest.raises(ShortwaveImportCancelled):
        apply_shortwave_import(store, preview, cancel_check=lambda: True)
    assert store.current_dataset() is None
    assert store.list_datasets() == ()


def test_sw1_same_bytes_reimport_is_idempotent_and_hash_versioned(tmp_path: Path) -> None:
    store = _store(tmp_path / "freqinout_nets.db")
    from freqinout.core.shortwave_import import apply_shortwave_import, preview_shortwave_import

    candidate = _parse_fixture()
    first_preview = preview_shortwave_import(store, candidate)
    first = apply_shortwave_import(store, first_preview)
    second_preview = preview_shortwave_import(store, candidate)
    second = apply_shortwave_import(store, second_preview)
    assert first.status == "promoted"
    assert second.status == "unchanged"
    assert second.dataset_key == first.dataset_key
    assert len(store.list_datasets(provider_key="eibi")) == 1
    assert first.dataset_key is not None
    assert first.dataset_key.endswith(candidate.csv_sha256[:20])


def test_sw1_failed_transaction_leaves_no_partial_current_dataset(tmp_path: Path) -> None:
    store = _store(tmp_path / "freqinout_nets.db")
    from freqinout.core.shortwave_import import apply_shortwave_import, preview_shortwave_import

    candidate = _parse_fixture()
    preview = preview_shortwave_import(store, candidate)
    with pytest.raises(RuntimeError, match="injected Shortwave import failure"):
        apply_shortwave_import(store, preview, fail_after_entries=1)
    assert store.current_dataset() is None
    assert store.list_datasets(provider_key="eibi") == ()


def test_sw1_retains_previous_dataset_for_explicit_rollback(tmp_path: Path) -> None:
    store = _store(tmp_path / "freqinout_nets.db")
    from freqinout.core.shortwave_import import (
        apply_shortwave_import,
        preview_shortwave_import,
        rollback_shortwave_dataset,
    )

    first_candidate = _parse_fixture(season_code="A26")
    first = apply_shortwave_import(store, preview_shortwave_import(store, first_candidate))
    second_candidate = _parse_fixture(season_code="B26", season_from="2026-10-25T00:00:00Z", season_to="2027-03-28T23:59:59Z")
    second = apply_shortwave_import(store, preview_shortwave_import(store, second_candidate))
    assert first.dataset_key and second.dataset_key and first.dataset_key != second.dataset_key
    assert store.current_dataset().dataset_key == second.dataset_key
    restored = rollback_shortwave_dataset(store, first.dataset_key)
    assert restored.status == "rolled_back"
    assert store.current_dataset().dataset_key == first.dataset_key


def test_sw1_ten_thousand_row_query_remains_bounded(tmp_path: Path) -> None:
    store = _store(tmp_path / "freqinout_nets.db")
    from freqinout.core.shortwave_import import apply_shortwave_import, preview_shortwave_import

    header = FIXTURE.read_bytes().splitlines()[0]
    row = b"9955;0000-2400;Mo;USA;Synthetic bounded row;EN;NA;USA;1;;"
    raw = b"\n".join([header, *(row for _ in range(10_000))]) + b"\n"
    candidate = _parse_bytes(raw)
    apply_shortwave_import(store, preview_shortwave_import(store, candidate))
    current = store.current_dataset()
    assert current is not None
    assert current.record_count == 10_000
    with sqlite3.connect(store.db_path) as conn:
        persisted_count = conn.execute(
            "SELECT COUNT(*) FROM shortwave_entries WHERE dataset_key=?",
            (current.dataset_key,),
        ).fetchone()[0]
    assert persisted_count == 10_000
    query = getattr(store, "list_entries", None) or getattr(store, "query_entries", None)
    assert callable(query)
    signature = inspect.signature(query)
    kwargs = {key: value for key, value in {
        "limit": 200,
        "page_size": 200,
        "search": "Synthetic",
        "frequency_hz": 9_955_000,
    }.items() if key in signature.parameters}
    started = time.perf_counter()
    rows = query(**kwargs)
    elapsed = time.perf_counter() - started
    assert len(rows) <= 200
    assert rows, "bounded read API must query the imported 10,000-row dataset"
    assert elapsed < 0.100, f"bounded Shortwave query took {elapsed * 1000:.1f} ms"


def test_sw1_db_initializer_is_additive_and_does_not_move_current_pointer(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    from freqinout.core import db_initializer
    from freqinout.core.resource_catalog_migration import resource_catalog_authority_state
    from freqinout.core.shortwave_import import apply_shortwave_import, preview_shortwave_import

    monkeypatch.setattr(db_initializer, "_config_dir", lambda: tmp_path)
    db_initializer.ensure_nets_tables()
    db_path = tmp_path / "freqinout_nets.db"
    store = _store(db_path)
    candidate = _parse_fixture()
    imported = apply_shortwave_import(store, preview_shortwave_import(store, candidate))
    assert imported.dataset_key is not None
    before_key = store.current_dataset().dataset_key
    with sqlite3.connect(db_path) as conn:
        conn.execute("CREATE TABLE migration_fixture (value TEXT NOT NULL)")
        conn.execute("INSERT INTO migration_fixture(value) VALUES ('keep')")
        conn.commit()

    db_initializer.ensure_nets_tables()

    assert resource_catalog_authority_state(db_path) == "canonical"
    assert store.current_dataset() is not None
    assert store.current_dataset().dataset_key == before_key
    with sqlite3.connect(db_path) as conn:
        assert conn.execute("SELECT value FROM migration_fixture").fetchone()[0] == "keep"
        assert conn.execute(
            "SELECT state FROM shortwave_datasets WHERE dataset_key=?", (before_key,)
        ).fetchone()[0] == "current"
